딕셔너리 만들 때 다음과 같은 입력 실수 발생.  **NameError** 오류 발생.

```python
>>> dict_key = {
		"name" : "캐치! 티니핑",
		"type" : "티니핑"
}
```

```python
Traceback (most recent call last):
	File "<pyshell#5>", line 2, in <module>
		name: "캐치! 티니핑",
NameError: naem 'name' is not defined
```

naem이라는 이름 정의되지 않았따는 오류.  
Python은 딕셔너리 키 따옴표 없이 단순하게 식별자를 입력하면 → 변수로 인식.  
오류 자체 해결하고 싶다면 name이라는 이름 변수 만들어 주면 됨. type은 type() 함수 기본 식별자 이것이 키로 들어가 따로 오류 발생하지 않음

```python
>>> name = "이름"
>>> dict_key = {
	"name" : "캐치! 티니핑",
	"type" : "티니핑"
}
>>> dict_key
{'이름': "캐치! 티니핑", <class 'type'>: "티니핑"}
```

일반적으로 이렇게 코드 안짬.